title: 洛奇的个人博客
author: slokis
email: 2583721977@qq.com
description: > # this means to ignore newlines until "show_exerpts:"
  这是一个个人的博客网站，博主目前是一名在校的大学生，学习着软件开发相关技术，网站会不定时更新博客文章，记录并学习相关知识。
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Mr.sLoki
  tagline: 不以物喜，不以己悲
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle

  # generate social links in footer
  social_links:
    #twitter: thelehhman
    github:  slokis
    #linkedIn: in/thelehhman
    rss: rss
    # dribbble: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed


valine_comment:
  enable: true
# app_id
  leancloud_appid: Uc83ft5SkTON6trrsfXsHjqE-gzGzoHsz
# app_key
  leancloud_appkey: 1fYLFpMD0Ut7S2RdDNl7ikbm
# placeholde
  placeholder: “Just go go"
